const ProductList = [
 "Acid",
 "Advanced Ion Battery",
 "Antimatter",
 "Antimatter Housing",
 "Carbon Nanotubes",
 "Circuit Board",
 "Di-hydrogen Jelly",
 "Glass",
 "Heat Capacitor",
 "Ion Battery",
 "Large Refiner",
 "Life Support Gel",
 "Liquid Explosive",
 "Living Glass",
 "Lubricant",
 "Medium Refiner",
 "Metal Plating",
 "Microprocessor",
 "Nanite Clusters",
 "Poly Fibre",
 "Portable Refiner",
 "Starship Launch Fuel",
 "TetraCobalt",
 "Unstable Gel",
 "Warp Cell",
];

module.exports = ProductList;
