// GENERATED FILE: Do not edit.

const ProductList = [
"Acid",
"Advanced Ion Battery",
"Albumen Pearl Orb",
"Ancient Key",
"Antimatter",
"Antimatter Housing",
"Aronium",
"AtlasPass v1",
"AtlasPass v2",
"AtlasPass v3",
"Awakenings",
"Captured Nanode",
"Carbon Crystal",
"Carbon Nanotubes",
"Chloride Lattice",
"Circuit Board",
"Cobalt Mirror",
"Cryo-Pump",
"Cryogenic Chamber",
"Dark Matter",
"Dawn's End",
"Defence Chit",
"Destablised Sodium",
"Di-hydrogen Jelly",
"Dirty Bronze",
"Drop Pod Coordinate Data",
"Echinocactus",
"Englobed Shade",
"Enriched Carbon",
"Expanding the Base",
"Explosive Drones",
"Fleet Command Room",
"Frigate Fuel (100 Tonnes)",
"Frigate Fuel (200 Tonnes)",
"Frostwort",
"Fuel Oxidiser",
"Fungal Cluster",
"Fusion Accelerant",
"Fusion Ignitor",
"Gamma Weed",
"Gek Relic",
"GekNip",
"Geodesite",
"Glass",
"Grantine",
"Gravitino Host",
"Heart of the Sun",
"Heat Capacitor",
"Hermetic Seal",
"Herox",
"Hex Core",
"Holographic Analyser",
"Hot Ice",
"Hydroponic Tray",
"Ion Battery",
"Iridesite",
"Korvax Casing",
"Korvax Convergence Cube",
"Large Hydroponic Tray",
"Large Refiner",
"Larval Core",
"Lemmium",
"Life Support Gel",
"Liquid Explosive",
"Living Glass",
"Lubricant",
"Magno-Gold",
"Medium Refiner",
"Metal Plating",
"Microprocessor",
"Mind Arc",
"Mind Control Device",
"Mineral Compressor",
"Modified Quanta",
"Mordite Root",
"Nanite Clusters",
"Navigation Data",
"Nitrogen Salt",
"Noospheric Orb",
"Novae Reclaiment",
"Organic Catalyst",
"Oxygen Capsule",
"Oxygen Filter",
"Photic Jade",
"Poly Fibre",
"Portable Reactor",
"Portable Refiner",
"Projectile Ammunition",
"Quantum Processor",
"Rare Metal Element",
"Salt Refractor",
"Salvaged Technology",
"Scientific Research",
"Semiconductor",
"Sentinel Quad",
"Sentinel Walker",
"Sodium Diode",
"Solar Vine",
"Standing Planter",
"Starship Launch Fuel",
"Stasis Device",
"State Phasure",
"Superconductor",
"Superoxide Crystal",
"Technology Module",
"TetraCobalt",
"Thermic Condensate",
"Unstable Gel",
"Unstable Plasma",
"Upgrade Module",
"Venom Urchin",
"Vy'keen Dagger",
"Vy'keen Effigy",
"Warp Cell",
"Weapons Research",
];

module.exports = ProductList;
