const ResourceList = [
 "Activated Cadmium",
 "Activated Copper",
 "Activated Emeril",
 "Activated Indium",
 "Ammonia",
 "Aronium",
 "Cactus Flesh",
 "Cadmium",
 "Carbon",
 "Carbon Crystal",
 "Chloride Lattice",
 "Chlorine",
 "Chromatic Metal",
 "Cobalt",
 "Condensed Carbon",
 "Copper",
 "Coprite",
 "Destablised Sodium",
 "Deuterium",
 "Di-hydrogen",
 "Dioxite",
 "Dirty Bronze",
 "Emeril",
 "Enriched Carbon",
 "Ferrite Dust",
 "Frost Crystal",
 "Fungal Mould",
 "Gamma Root",
 "Geodesite",
 "Gold",
 "Grantine",
 "Herox",
 "Hexite",
 "Ionised Cobalt",
 "Indium",
 "Iridesite",
 "Kelp Sac",
 "Lemmium",
 "Living Slime",
 "Magnetised Ferrite",
 "Magno-Gold",
 "Marrow Bulb",
 "Mordite",
 "Nitrogen",
 "Nitrogen Salt",
 "Oxygen",
 "Paraffinium",
 "Phosphorus",
 "Platinum",
 "Pugneum",
 "Pure Ferrite",
 "Pyrite",
 "Radon",
 "Rare Metal Element",
 "Residual Goop",
 "Runaway Mould",
 "Rusted Metal",
 "Salt",
 "Silver",
 "Sodium",
 "Sodium Nitrate",
 "Solanium",
 "Star Bulb",
 "Sulphurine",
 "Superoxide Crystal",
 "Thermic Condensate",
 "Tritium",
 "Unstable Plasma",
 "Uranium",
 "Viscous Fluids",
];

module.exports = ResourceList;
