// for baseValue see https://nomanssky.gamepedia.com/Resource

const Resource = {
  ACTIVATED_CADMIUM: "activatedCadmium",
  ACTIVATED_COPPER: "activatedCopper",
  ACTIVATED_EMERIL: "activatedEmeril",
  ACTIVATED_INDIUM: "activatedIndium",
  AMMONIA: "ammonia",
  ARONIUM: "aronium",
  CACTUS_FLESH: "cactusFlesh",
  CADMIUM: "cadmium",
  CARBON: "carbon",
  CARBON_CRYSTAL: "carbonCrystal",
  CHLORIDE_LATTICE: "chlorideLattice",
  CHLORINE: "chlorine",
  CHROMATIC_METAL: "chromaticMetal",
  COBALT: "cobalt",
  CONDENSED_CARBON: "condensedCarbon",
  COPPER: "copper",
  COPRITE: "coprite",
  DESTABLISED_SODIUM: "destablisedSodium",
  DEUTERIUM: "deuterium",
  DI_HYDROGEN: "diHydrogen",
  DIOXITE: "dioxite",
  DIRTY_BRONZE: "dirtyBronze",
  EMERIL: "emeril",
  ENRICHED_CARBON: "enrichedCarbon",
  FERRITE_DUST: "ferriteDust",
  FROST_CRYSTAL: "frostCrystal",
  FUNGAL_MOULD: "fungalMould",
  GAMMA_ROOT: "gammaRoot",
  GEODESITE: "geodesite",
  GOLD: "gold",
  GRANTINE: "grantine",
  HEROX: "herox",
  HEXITE: "hexite",
  IONISED_COBALT: "ionisedCobalt",
  INDIUM: "indium",
  IRIDESITE: "iridesite",
  KELP_SAC: "kelpSac",
  LEMMIUM: "lemmium",
  LIVING_SLIME: "livingSlime",
  MAGNETISED_FERRITE: "magnetisedFerrite",
  MAGNO_GOLD: "magnoGold",
  MARROW_BULB: "marrowBulb",
  MORDITE: "mordite",
  NITROGEN: "nitrogen",
  NITROGEN_SALT: "nitrogenSalt",
  OXYGEN: "oxygen",
  PARAFFINIUM: "paraffinium",
  PHOSPHORUS: "phosphorus",
  PLATINUM: "platinum",
  PUGNEUM: "pugneum",
  PURE_FERRITE: "pureFerrite",
  PYRITE: "pyrite",
  RADON: "radon",
  RARE_METAL_ELEMENT: "rareMetalElement",
  RESIDUAL_GOOP: "residualGoop",
  RUNAWAY_MOULD: "runawayMould",
  RUSTED_METAL: "rustedMetal",
  SALT: "salt",
  SILVER: "silver",
  SODIUM: "sodium",
  SODIUM_NITRATE: "sodiumNitrate",
  SOLANIUM: "solanium",
  STAR_BULB: "starBulb",
  SULPHURINE: "sulphurine",
  SUPEROXIDE_CRYSTAL: "superoxideCrystal",
  THERMIC_CONDENSATE: "thermicCondensate",
  TRITIUM: "tritium",
  UNSTABLE_PLASMA: "unstablePlasma",
  URANIUM: "uranium",
  VISCOUS_FLUIDS: "viscousFluids"
};

Resource.properties = {
  activatedCadmium: { name: "Activated Cadmium" },
  activatedCopper: { name: "Activated Copper" },
  activatedEmeril: { name: "Activated Emeril" },
  activatedIndium: { name: "Activated Indium" },
  ammonia: { name: "Ammonia", baseValue: 62 },
  aronium: { name: "Aronium" },
  cactusFlesh: { name: "Cactus Flesh", baseValue: 28 },
  cadmium: { name: "Cadmium", baseValue: 234 },
  carbon: { name: "Carbon", baseValue: 7 },
  carbonCrystal: { name: "Carbon Crystal" },
  chlorideLattice: { name: "Chloride Lattice" },
  chlorine: { name: "Chlorine", baseValue: 602 },
  chromaticMetal: { name: "Chromatic Metal", baseValue: 245 },
  cobalt: { name: "Cobalt", baseValue: 198 },
  condensedCarbon: { name: "Condensed Carbon", baseValue: 24 },
  copper: { name: "Copper", baseValue: 110 },
  coprite: { name: "Coprite", baseValue: 30 },
  destablisedSodium: { name: "Destablised Sodium" },
  deuterium: { name: "Deuterium", baseValue: 34 },
  diHydrogen: { name: "Di-hydrogen", baseValue: 34 },
  dioxite: { name: "Dioxite", baseValue: 62 },
  dirtyBronze: { name: "Dirty Bronze", baseValue: 25000 },
  emeril: { name: "Emeril", baseValue: 275 },
  enrichedCarbon: { name: "Enriched Carbon" },
  ferriteDust: { name: "Ferrite Dust", baseValue: 14 },
  frostCrystal: { name: "Frost Crystal", baseValue: 12 },
  fungalMould: { name: "Fungal Mould", baseValue: 16 },
  gammaRoot: { name: "Gamma Root", baseValue: 16 },
  geodesite: { name: "Geodesite" },
  gold: { name: "Gold", baseValue: 202 },
  grantine: { name: "Grantine" },
  herox: { name: "Herox", baseValue: 25000 },
  hexite: { name: "Hexite" },
  ionisedCobalt: { name: "Ionised Cobalt", baseValue: 401 },
  indium: { name: "Indium", baseValue: 464 },
  iridesite: { name: "Iridesite" },
  kelpSac: { name: "Kelp Sac", baseValue: 41 },
  lemmium: { name: "Lemmium" },
  livingSlime: { name: "Living Slime", baseValue: 20 },
  magnetisedFerrite: { name: "Magnetised Ferrite", baseValue: 82 },
  magnoGold: { name: "Magno-Gold", baseValue: 25000 },
  marrowBulb: { name: "Marrow Bulb", baseValue: 41 },
  mordite: { name: "Mordite", baseValue: 40 },
  nitrogen: { name: "Nitrogen", baseValue: 20 },
  nitrogenSalt: { name: "Nitrogen Salt" },
  oxygen: { name: "Oxygen", baseValue: 34 },
  paraffinium: { name: "Paraffinium", baseValue: 62 },
  phosphorus: { name: "Phosphorus", baseValue: 62 },
  platinum: { name: "Platinum", baseValue: 303 },
  pugneum: { name: "Pugneum", baseValue: 138 },
  pureFerrite: { name: "Pure Ferrite", baseValue: 28 },
  pyrite: { name: "Pyrite", baseValue: 62 },
  radon: { name: "Radon", baseValue: 20 },
  rareMetalElement: { name: "Rare Metal Element" },
  residualGoop: { name: "Residual Goop", baseValue: 20 },
  runawayMould: { name: "Runaway Mould", baseValue: 20 },
  rustedMetal: { name: "Rusted Metal", baseValue: 20 },
  salt: { name: "Salt", baseValue: 299 },
  silver: { name: "Silver", baseValue: 101 },
  sodium: { name: "Sodium", baseValue: 41 },
  sodiumNitrate: { name: "Sodium Nitrate", baseValue: 82 },
  solanium: { name: "Solanium", baseValue: 70 },
  starBulb: { name: "Star Bulb", baseValue: 32 },
  sulphurine: { name: "Sulphurine", baseValue: 20 },
  superoxideCrystal: { name: "Superoxide Crystal" },
  thermicCondensate: { name: "Thermic Condensate" },
  tritium: { name: "Tritium", baseValue: 6 },
  unstablePlasma: { name: "Unstable Plasma" },
  uranium: { name: "Uranium", baseValue: 62 },
  viscousFluids: { name: "Viscous Fluids", baseValue: 20 }
};

Object.freeze(Resource);

export default Resource;
